<?xml version="1.0"?>
<robot name="c2" xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- Import common colors -->
	<xacro:include filename="$(find c2_hw)/urdf/common.xacro" />
	
	<!-- Constants for robot dimensions -->
	<xacro:property name="base_size_x" value="0.255" /> <!-- in m-->
	<xacro:property name="base_size_y" value="0.149" />
	<xacro:property name="base_size_z" value="0.09" />
	<xacro:property name="wheel_width" value="0.026" /> 
	<xacro:property name="wheel_diameter" value="0.066" />
	<xacro:property name="wheel_mass" value="0.2" /> <!-- in kg-->
	<xacro:property name="wheel_axis_front" value="0.077" />
	<xacro:property name="wheel_axis_width" value="0.106" />
	<xacro:property name="chassis_high" value="0.045" />

	<!-- define macro -->
	<xacro:macro name="default_inertial" params="mass">
		<inertial>
			<mass value="${mass}" />
			<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="cylinder_inertia" params="mass r h">
		<inertial>
			<mass value="${mass}" />
			<origin xyz="0 0 0" />
			<inertia  ixx="${mass*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${mass*(3*r*r+h*h)/12}" iyz = "0" izz="${mass*r*r/2}" /> 
		</inertial>
	</xacro:macro>
     
	<xacro:macro name="wheel" params="parent side reflect color">
		<link name="wheel_${side}_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
				</geometry>
				<material name="${color}" />
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
				</geometry>
			</collision>
			<xacro:cylinder_inertia  mass="${wheel_mass}" r="${wheel_diameter/2}" h="${wheel_width}" />
		</link>
		
		<joint name="wheel_${side}_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="wheel_${side}_link"/>
			<origin xyz="${base_size_x/2-wheel_axis_front} ${reflect*(wheel_axis_width+wheel_width)/2} ${wheel_diameter/2-(base_size_z/2+chassis_high)}" rpy="${-1*PI/2} 0 0" />
			<axis xyz="0 0 1" />
			<limit effort="100" velocity="100"/>
			<safety_controller k_velocity="10" />
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>
		
		<transmission name="wheel_${side}_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="wheel_${side}_joint" >
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="wheel_${side}_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>

	<!-- The Base footprint -->
	<link name="base_footprint">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.05 0.05 0.001" />
			</geometry>
			<material name="TransparentGreen" />
		</visual>
	</link>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${chassis_high + base_size_z/2}" rpy="0 0 0" />
		<parent link="base_footprint"/>
		<child link="base_link" />
	</joint>
	
	<!-- The Base -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${base_size_x} ${base_size_y} ${base_size_z}" />
			</geometry>
			<material name="TransparentSkyBlue" />
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${base_size_x} ${base_size_y} ${base_size_z}" />
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
	</link>

	<!-- the driving wheels -->
	<xacro:wheel parent="base_link" side="left" reflect="1" color="Orange"/>
	<xacro:wheel parent="base_link" side="right" reflect="-1" color="Orange"/>
	
	<!-- the non-driving wheels -->
	<link name="wheel_tail_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<sphere radius="${chassis_high/2}" />
			</geometry>
			<material name="Orange" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${chassis_high/2}" />
			</geometry>
		</collision>
		<xacro:default_inertial mass="0.01"/>
	</link>

	<joint name="wheel_tail_joint" type="fixed">
		<parent link="base_link"/>
		<child link="wheel_tail_link"/>
		<origin xyz="${-1*(base_size_x/2 - 0.05)} 0 ${-1*(base_size_z+chassis_high)/2}" rpy="0 0 0" />
		<axis xyz="0 0 1" />
		<limit effort="100" velocity="100" lower="0.0" upper="314" />
	</joint>

	<!-- Camera -->
	<link name="camera_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
			<material name="red">
				<color rgba="1 0 0 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>

	<joint name="camera_joint" type="fixed">
		<axis xyz="0 1 0" />
		<origin xyz="${(base_size_x-0.05)/2} 0 ${(base_size_z + 0.05)/2 }" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="camera_link"/>
	</joint>
	
	<!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
	so that ros and opencv can operate on the camera frame correctly -->
	<link name="camera_link_optical" />
	
	<joint name="camera_optical_joint" type="fixed">
		<!-- these values have to be these values otherwise the gazebo camera image
		won't be aligned properly with the frame it is supposedly originating from -->
		<origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
		<parent link="camera_link"/>
		<child link="camera_link_optical"/>
	</joint>

	<!-- Hokuyo Laser -->
	<link name="hokuyo_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://my_common/meshes/hokuyo.dae"/>
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>

	<joint name="hokuyo_joint" type="fixed">
		<axis xyz="0 1 0" />
		<origin xyz="${(base_size_x-0.05)/2} 0.05 ${(base_size_z + 0.07)/2}" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="hokuyo_link"/>
	</joint>

	<!-- Import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find c2_hw)/urdf/c2.gazebo" />
	
</robot>


